server {
    listen ${PORT};
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    absolute_redirect off;

    location /globe {
        try_files /globe/index.html =404;
    }

    location /invest {
        try_files /invest/index.html =404;
    }

    location / {
        return 301 /globe;
    }

    gzip on;
    gzip_types text/html text/css application/javascript;
    gzip_min_length 1024;
}
